language: cpp

compiler:
  - gcc
  - clang

before_install:
  - gem install sass
  - git clone https://github.com/sass/libsass.git
  - cd libsass && git submodule init && git submodule update && cd ..
  - export SASS_LIBSASS_PATH=libsass
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - make test
